Repository Leets-Official/Yes-FE, pull requests merged in 2025-02, with the labels that each got.

#36 #31 feat: 초대장 생성하기 api 연결
  package.json
  src/api/usePostInvitation.tsx
  src/components/create/TemplateFront.tsx
  src/components/result/InvitationBack.tsx
  src/components/result/QRShareButton.tsx
  src/data/Template.ts
  src/hooks/getISOString.tsx
  src/hooks/useCanvas.tsx
  src/pages/Result.tsx
  src/pages/create/CreateBack.tsx
  src/type/TemplateType.ts
  yarn.lock
Labels: ✨ Feature

#39 #35 feat : 초대장 상세조회 API
  src/App.tsx
  src/api/errorCode.ts
  src/api/useGetAttendees.tsx
  src/api/useGetInvitation.tsx
  src/api/useGetInvitationList.tsx
  src/components/layout/InvitationHeader.tsx
  src/components/mypage/AttendeeList.tsx
  src/components/mypage/InvitationOverview.tsx
  src/components/result/CopyLinkButton.tsx
  src/components/result/QRShareButton.tsx
  src/pages/create/CreateFront.tsx
  src/pages/create/CreateNickname.tsx
  src/pages/create/CreateTemplate.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  src/pages/mypage/MyPageMain.tsx
  src/type/types.d.ts
  src/utils/customAxios.ts
Labels: 🔨 Refactor, 📬 API, 🎨 Html&css

#40 #39 feat: 디데이 구현 및 디자인 수정
  src/App.tsx
  src/assets/speachBubble.svg
  src/components/common/CustomToast.tsx
  src/components/common/InvitationCard.tsx
  src/components/result/CopyLinkButton.tsx
  src/components/result/KaKaoShareButton.tsx
  src/components/result/QRShareButton.tsx
  src/components/result/ShareButtonStyle.tsx
  src/components/result/ShareList.tsx
  src/pages/ReceiveInvitation.tsx
  src/pages/Result.tsx
  src/pages/create/CreateBack.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/type/types.d.ts
  src/utils/customAxios.ts
Labels: ✨ Feature, 🎨 Html&css

#43 #42 fix: 상세조회 res 수정 및 초대장 생성이슈 해결
  src/api/usePostInvitation.tsx
  src/atom/InvitationInfo.ts
  src/components/layout/InvitationHeader.tsx
  src/components/layout/MyPageHeader.tsx
  src/components/mypage/InvitationOverview.tsx
  src/hooks/useCanvas.tsx
  src/pages/create/CreateBack.tsx
  src/pages/create/CreateTemplate.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  src/pages/mypage/MyPageMain.tsx
  src/type/types.d.ts
  src/utils/customAxios.ts
  src/utils/formatDate.ts
Labels: 🐞 BugFix

#45 #44 refactor : 로딩 컴포넌트 추가 및 QA(+디자인) 수정
  public/home_logo.svg
  public/image/small_yes.svg
  public/image/yes.svg
  src/App.tsx
  src/api/fetchData.ts
  src/api/useDeleteInvitation.tsx
  src/api/useGetAttendees.tsx
  src/api/useGetInvitation.tsx
  src/api/useGetInvitationList.tsx
  src/api/useGetMyAttendance.tsx
  src/api/useGetMyPageInfo.tsx
  src/api/useGetQR.tsx
  src/components/common/AttendeeItem.tsx
  src/components/common/InvitationCard.tsx
  src/components/common/Skeleton.tsx
  src/components/create/TemplateFront.tsx
  src/components/create/TemplatePreview.tsx
  src/components/layout/MyPageHeader.tsx
  src/components/mypage/InvitationOverview.tsx
  src/components/result/InvitationFront.tsx
  src/pages/Home.tsx
  src/pages/Loading.tsx
  src/pages/create/CreateNickname.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  src/pages/mypage/MyPageMain.tsx
  src/routes/PrivateRoutes.tsx
Labels: 🔨 Refactor, 🎨 Html&css
