Repository Leets-Official/Yes-FE, pull requests merged in 2025-01, with the labels that each got.

#4 #2 feat: 카카오로그인 및 랜딩페이지 구현완료
  package.json
  src/App.tsx
  src/assets/font/Pretendard-Black.otf
  src/assets/font/Pretendard-Black.ttf
  src/assets/font/Pretendard-Black.woff
  src/assets/font/Pretendard-Bold.otf
  src/assets/font/Pretendard-Bold.ttf
  src/assets/font/Pretendard-Bold.woff
  src/assets/font/Pretendard-ExtraBold.otf
  src/assets/font/Pretendard-ExtraBold.ttf
  src/assets/font/Pretendard-ExtraBold.woff
  src/assets/font/Pretendard-ExtraLight.otf
  src/assets/font/Pretendard-ExtraLight.ttf
  src/assets/font/Pretendard-ExtraLight.woff
  src/assets/font/Pretendard-Light.otf
  src/assets/font/Pretendard-Light.ttf
  src/assets/font/Pretendard-Light.woff
  src/assets/font/Pretendard-Medium.otf
  src/assets/font/Pretendard-Medium.ttf
  src/assets/font/Pretendard-Medium.woff
  src/assets/font/Pretendard-Regular.otf
  src/assets/font/Pretendard-Regular.ttf
  src/assets/font/Pretendard-Regular.woff
  src/assets/font/Pretendard-SemiBold.otf
  src/assets/font/Pretendard-SemiBold.ttf
  src/assets/font/Pretendard-SemiBold.woff
  src/assets/font/Pretendard-Thin.otf
  src/assets/font/Pretendard-Thin.ttf
  src/assets/font/Pretendard-Thin.woff
  src/assets/font/font.css
  src/assets/image/yes.svg
  src/components/common/Button.tsx
  src/components/layout/HomeHeader.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/login/KakaoRedirectHandler.tsx
  src/pages/login/Login.tsx
  src/utils/cookies.ts
  src/utils/index.tsx
  yarn.lock
Labels: ✨ Feature

#7 #5 feat: 초대장 뒷면 정보 입력
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/TextArea.tsx
  src/components/result/InvitationBack.tsx
  src/index.css
  src/pages/create/CreateBack.tsx
  src/pages/create/InvitationCreate.tsx
Labels: ✨ Feature

#8 #6 feat: 초대장 앞면 정보 입력
  package.json
  public/image/template_example.png
  public/image/template_example2.png
  public/image/yes.svg
  src/App.tsx
  src/atom/InvitationInfo.ts
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/TextArea.tsx
  src/components/create/TemplatePreview.tsx
  src/components/layout/InvitationHeader.tsx
  src/data/Template.ts
  src/pages/Home.tsx
  src/pages/create/CreateFront.tsx
  src/pages/create/CreateNickname.tsx
  src/pages/create/CreateTemplate.tsx
  src/pages/create/InvitationCreate.tsx
  src/pages/login/Login.tsx
  src/type/index.tsx
  src/type/types.d.ts
  yarn.lock
Labels: ✨ Feature

#10 #9 feat: 마이페이지 UI 구현
  public/image/small_yes.svg
  src/App.tsx
  src/components/layout/MyPageHeader.tsx
  src/components/mypage/AttendeeList.tsx
  src/components/mypage/InvitationOverview.tsx
  src/components/mypage/InvitationStats.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageMain.tsx
Labels: ✨ Feature

#13 #11 feat: 초대장 앞면 수정사항 완료
  public/image/Invi_Alien.png
  public/image/Invi_Chirashi.png
  public/image/Invi_Cyber.png
  public/image/Invi_Princess.png
  public/image/Invi_Rabbit.png
  public/image/Invi_Receipt.png
  public/image/Pre_Invi_Alien.png
  public/image/Pre_Invi_Chirashi.png
  public/image/Pre_Invi_Cyber.png
  public/image/Pre_Invi_Princess.png
  public/image/Pre_Invi_Rabbit.png
  public/image/Pre_Invi_Receipt.png
  public/image/yes.svg
  src/assets/font/font.css
  src/atom/InvitationInfo.ts
  src/components/common/TextArea.tsx
  src/components/create/TemplateFront.tsx
  src/components/create/TemplatePreview.tsx
  src/data/Template.ts
  src/hooks/index.tsx
  src/hooks/useResetStepState.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/create/CreateBack.tsx
  src/pages/create/CreateFront.tsx
  src/pages/create/CreateNickname.tsx
  src/pages/create/CreateTemplate.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/InvitationDetail.tsx
Labels: ✨ Feature, 🎨 Html&css

#14 #12 feat 초대장 작성 완료 디자인 반영
  src/App.tsx
  src/assets/QRsahre.svg
  src/assets/copylink.svg
  src/assets/kakaoshare.svg
  src/components/common/Input.tsx
  src/components/layout/InvitationHeader.tsx
  src/components/layout/MyPageHeader.tsx
  src/components/result/CopyLinkButton.tsx
  src/components/result/InvitationBack.tsx
  src/components/result/InvitationFront.tsx
  src/components/result/KaKaoShareButton.tsx
  src/components/result/QRShareButton.tsx
  src/components/result/ShareList.tsx
  src/pages/Result.tsx
  src/pages/create/CreateBack.tsx
  src/pages/mypage/MyPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#18 #16 feat 초대장 데이터 폰트 크기+컬러 속성 추가
  package.json
  src/App.tsx
  src/components/create/TemplateFront.tsx
  src/components/create/TemplatePreview.tsx
  src/components/layout/HomeHeader.tsx
  src/components/layout/MyPageHeader.tsx
  src/data/Template.ts
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/create/CreateNickname.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#20 #17 feat: 초대받기 플로우 구현
  src/App.tsx
  src/assets/speachBubble.svg
  src/components/common/InvitationCard.tsx
  src/components/common/Modal.tsx
  src/components/result/InvitationFront.tsx
  src/pages/ReceiveInvitation.tsx
  src/pages/Result.tsx
  src/pages/create/CreateBack.tsx
Labels: ✨ Feature, 🎨 Html&css

#22 #19 feat: 카카오로그인 API 구현
  package.json
  src/App.tsx
  src/assets/NotFoundImg.svg
  src/atom/InvitationInfo.ts
  src/atom/UserInfo.ts
  src/components/error/DefaultError.tsx
  src/pages/ErrorFallback.tsx
  src/pages/ErrorPage.tsx
  src/pages/login/KakaoRedirectHandler.tsx
  src/pages/login/Login.tsx
  src/routes/PrivateRoutes.tsx
  src/utils/customAxios.ts
  src/utils/isAccessToken.ts
  yarn.lock
Labels: ✨ Feature, 📬 API

#26 #25 feat: axios 에러 처리 로직 추가
  src/api/errorCode.ts
  src/api/fetchData.ts
  src/pages/ErrorFallback.tsx
  src/utils/customAxios.ts
Labels: ✨ Feature, 📬 API

#27 #24 feat: 카카오톡으로 공유하기
  index.html
  public/icon.svg
  public/image/Invi_Alien.png
  public/image/Invi_Chirashi.png
  public/image/Invi_Cyber.png
  public/image/Invi_Princess.png
  public/image/Invi_Rabbit.png
  public/image/Invi_Receipt.png
  public/image/Pre_Invi_Alien.png
  public/image/Pre_Invi_Chirashi.png
  public/image/Pre_Invi_Cyber.png
  public/image/Pre_Invi_Princess.png
  public/image/Pre_Invi_Rabbit.png
  public/image/Pre_Invi_Receipt.png
  public/image/template_example.png
  public/image/template_example2.png
  src/App.tsx
  src/components/result/CopyLinkButton.tsx
  src/components/result/KaKaoShareButton.tsx
  src/components/result/ShareList.tsx
  src/pages/Result.tsx
  src/type/kakao.d.ts
Labels: ✨ Feature

#30 #29 feat: 뒷면 유효성 검사 및 UI 수정
  src/components/common/DateInput.tsx
  src/components/common/ErrorPhrase.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/TextArea.tsx
  src/components/result/KaKaoShareButton.tsx
  src/components/result/QRShareButton.tsx
  src/hooks/useValidation.tsx
  src/pages/create/CreateBack.tsx
  src/pages/create/CreateNickname.tsx
Labels: ✨ Feature

#34 #32 feat: qr 조회 api 연결
  src/App.tsx
  src/api/useGetQR.tsx
  src/components/common/InvitationCard.tsx
  src/components/result/InvitationFront.tsx
  src/components/result/QRShareButton.tsx
  src/pages/ReceiveInvitation.tsx
  src/pages/Result.tsx
  src/utils/customAxios.ts
Labels: ✨ Feature

#33 #28 feat: 마이페이지 API 및 UI 수정
  public/home_logo.svg
  public/image/Invi_Alien.png
  public/image/Pre_Invi_Alien.png
  src/App.tsx
  src/api/index.tsx
  src/api/useDeleteInvitation.tsx
  src/api/useGetInvitationList.tsx
  src/api/useGetMyPageInfo.tsx
  src/components/layout/MyPageHeader.tsx
  src/components/mypage/AttendeeList.tsx
  src/components/mypage/InvitationOverview.tsx
  src/components/mypage/InvitationStats.tsx
  src/components/result/InvitationBack.tsx
  src/data/Template.ts
  src/pages/Home.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/InvitationDetail.tsx
  src/pages/mypage/InvitationList.tsx
  src/pages/mypage/MyPageMain.tsx
  src/type/types.d.ts
  src/utils/customAxios.ts
  src/utils/formatDate.ts
Labels: ✨ Feature, 📬 API, 🎨 Html&css
